spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/learn?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 12345678
#公共配置与profiles选择无关
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    call-setters-on-nulls: true
# <!-- knife4j 接入STEP ③：配置文件开启Knife4j -->
knife4j:
  # 为了生产环境接口安全,需要屏蔽所有Swagger的相关资源,生产环境设置为true
  production: false
  enable: true
  setting:
    # 开启器分组，让@ApiSort(int序号)控制controller排序展示
    enableGroup: true
# 【配置中心】NACOS
nacos:
  config:
    server-addr: 127.0.0.1:8848
    namespace: b236ec2d-c656-4d14-a567-7a17a80399d0
# 【非关系型数据库】Redis jedis wiki：https://github.com/redis/jedis/wiki
redis:
  hostname: 127.0.0.1
  port: 6379
  password:
  # 最大链接时间
  maxactive: 100
  #最大空闲链接数
  maxidleConnection: 100
  #最小空闲链接数 初始化链接数
  minidleConnection: 5
  #空闲毫秒数进行链接回收 1min
  minEvictableIdleTimeMillis: 60000
  #等待链接的最长时间毫秒值
  maxwaitMillis: 1000
