use learn;
CREATE TABLE `u_userinfo`
(
    `id`                 bigint(20)                                              NOT NULL,
    `username`           varchar(45) CHARACTER SET utf8 COLLATE utf8_general_ci           DEFAULT NULL COMMENT '用户名',
    `smallname`          varchar(45) CHARACTER SET utf8 COLLATE utf8_general_ci           DEFAULT '',
    `head`               varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci          DEFAULT NULL COMMENT '用户头像',
    `pinyin`             varchar(45) CHARACTER SET utf8 COLLATE utf8_general_ci           DEFAULT NULL COMMENT '用户拼音',
    `password`           varchar(45) CHARACTER SET utf8 COLLATE utf8_general_ci           DEFAULT '',
    `number`             varchar(45) CHARACTER SET utf8 COLLATE utf8_general_ci           DEFAULT '',
    `mobile`             varchar(45) CHARACTER SET utf8 COLLATE utf8_general_ci           DEFAULT NULL COMMENT '手机号',
    `mobile_local`       varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '号码归属地json',
    `weixin`             varchar(45) CHARACTER SET utf8 COLLATE utf8_general_ci           DEFAULT NULL COMMENT '用户微信号',
    `s0`                 int(11)                                                          DEFAULT '0',
    `s1`                 int(11)                                                          DEFAULT '0',
    `s2`                 int(11)                                                          DEFAULT '0',
    `s3`                 int(11)                                                          DEFAULT '0',
    `s4`                 int(11)                                                          DEFAULT '0',
    `s5`                 int(11)                                                          DEFAULT '0',
    `s6`                 int(11)                                                          DEFAULT '0',
    `type`               int(11)                                                          DEFAULT '0',
    `status`             int(11)                                                          DEFAULT '0',
    `substatus`          int(11)                                                          DEFAULT '0',
    `orther`             text CHARACTER SET utf8 COLLATE utf8_general_ci,
    `note`               text CHARACTER SET utf8 COLLATE utf8_general_ci COMMENT '沟通记录',
    `note_time`          int(11)                                                          DEFAULT NULL COMMENT '最近一次沟通时间',
    `ctime`              int(11)                                                          DEFAULT NULL COMMENT '线索创建时间',
    `utime`              int(11)                                                          DEFAULT NULL COMMENT '线索修改时间',
    `cid`                bigint(20)                                                       DEFAULT NULL COMMENT '线索 创建操作者ID 系统创建为0',
    `mid`                bigint(20)                                                       DEFAULT NULL COMMENT '线索 修改者操作ID',
    `channel`            varchar(45) CHARACTER SET utf8 COLLATE utf8_general_ci           DEFAULT NULL COMMENT '线索所在渠道ID',
    `come`               varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci          DEFAULT NULL,
    `newsource`          varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci          DEFAULT NULL,
    `source`             varchar(45) CHARACTER SET utf8 COLLATE utf8_general_ci           DEFAULT '',
    `master`             bigint(20)                                                       DEFAULT NULL COMMENT '所负责用户的班主任',
    `teacher`            bigint(255)                                                      DEFAULT NULL COMMENT '所负责用户的老师',
    `sales`              bigint(20)                                                       DEFAULT '0' COMMENT '所负责用户的课程顾问',
    `province`           varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci          DEFAULT NULL COMMENT '线索所在省份',
    `city`               varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci          DEFAULT NULL COMMENT '线索所在城市',
    `area`               varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci          DEFAULT '',
    `street`             varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci          DEFAULT '',
    `address`            varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci          DEFAULT NULL COMMENT '用户收货地址 已摒弃',
    `created`            int(11)                                                          DEFAULT '0',
    `updated`            int(11)                                                          DEFAULT '0',
    `bycreated`          bigint(20)                                                       DEFAULT '0',
    `byupdated`          bigint(20)                                                       DEFAULT '0',
    `payment`            int(11)                                                          DEFAULT NULL COMMENT '是否缴费 1：是 0：否',
    `flowstatus`         int(11)                                                          DEFAULT NULL COMMENT '用户状态 0：失效,1：未分配,2：待跟进,3：跟进中,4：已邀约,5：已试听,6：已缴费',
    `exp_num`            varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci          DEFAULT NULL COMMENT '发货单号',
    `expstatus`          int(11)                                                          DEFAULT NULL COMMENT '发货状态 0：待审核,1：已发货,2：已签收,3：配送失败,4：审核失败,5：已审核',
    `del`                int(11)                                                          DEFAULT '0' COMMENT '是否删除 1：是 0：否',
    `again_time`         int(11)                                                          DEFAULT '0' COMMENT '记录线索二次领取试听的时间',
    `status_tags`        varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci          DEFAULT '0' COMMENT '状态标签',
    `lessonstatus`       int(11)                                                          DEFAULT '0',
    `lessonexstatus`     int(11)                                                          DEFAULT '0',
    `exp_time`           int(11)                                                          DEFAULT '0' COMMENT '快递状态更新时间',
    `f_lesson_time`      int(11)                                                          DEFAULT NULL COMMENT '用户最后一次上课时间',
    `f_buy_time`         int(11)                                                          DEFAULT NULL COMMENT '用户购买课时的时间',
    `life`               int(11)                                                 NOT NULL DEFAULT '0',
    `apk`                int(11)                                                          DEFAULT '0',
    `pc`                 int(11)                                                          DEFAULT '0',
    `fp_count`           tinyint(3) unsigned                                     NOT NULL DEFAULT '0' COMMENT '再分配次数',
    `equ`                varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci          DEFAULT '0' COMMENT '已有设备',
    `lessonequ`          varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci          DEFAULT '0' COMMENT '上课设备',
    `fp_time`            int(10) unsigned                                        NOT NULL DEFAULT '0' COMMENT '分配时间',
    `fp_tags`            varchar(120) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '分配标签',
    `fp_auto`            tinyint(3) unsigned                                     NOT NULL DEFAULT '1' COMMENT '是否开启自动分配1-开户，0-关闭',
    `fp_province`        varchar(12) CHARACTER SET utf8 COLLATE utf8_general_ci  NOT NULL DEFAULT '' COMMENT '分配所需省份',
    `fp_city`            varchar(12) CHARACTER SET utf8 COLLATE utf8_general_ci  NOT NULL DEFAULT '' COMMENT '分配所需市级',
    `region`             varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci           DEFAULT NULL COMMENT '线索所被分配的城市',
    `buyid`              bigint(20)                                                       DEFAULT '0',
    `buyregtype`         int(11)                                                          DEFAULT '0',
    `buystatus`          int(11)                                                          DEFAULT '0',
    `point`              tinyint(4)                                              NOT NULL DEFAULT '0' COMMENT '是否重点客户，0：否；1：是',
    `isactive`           tinyint(4)                                              NOT NULL DEFAULT '0' COMMENT '是否激活；1激活；2未激活；（电话接通为激活，电话未接通为未激活）',
    `havemind`           tinyint(4)                                              NOT NULL DEFAULT '0' COMMENT '是否有意向',
    `camera`             varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '0' COMMENT '镜头版本，0老版;',
    `serverinfo`         text CHARACTER SET utf8 COLLATE utf8_general_ci COMMENT '线索入库时的server信息',
    `bosswarning`        tinyint(4)                                              NOT NULL DEFAULT '0' COMMENT 'boss警告',
    `bosstime`           int(11)                                                 NOT NULL DEFAULT '0' COMMENT 'boss库线索创建时间',
    `parent`             bigint(20)                                                       DEFAULT NULL COMMENT '用户的父ID，主要针对于有子账号得用户',
    `pc_script`          tinyint(4)                                              NOT NULL DEFAULT '0' COMMENT '是否PC线索，通过跑脚本得出2018-7-2',
    `android_script`     tinyint(4)                                              NOT NULL DEFAULT '0' COMMENT '是否android线索，通过跑脚本得出2018-7-2',
    `areacode`           varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci           DEFAULT NULL COMMENT '线索所在国家电话区号前缀',
    `tmk`                int(11)                                                          DEFAULT '0' COMMENT '所负责用户的tmk',
    `tmkpool`            int(11)                                                          DEFAULT '0' COMMENT 'TMK池,0:默认,未入TMK池;1:已入TMK池',
    `tmkstime`           int(11)                                                          DEFAULT '0' COMMENT '线索入TMK池时间',
    `tmkltime`           int(11)                                                          DEFAULT '0' COMMENT '线索出TMK池时间',
    `screenshot`         tinyint(1)                                                       DEFAULT NULL COMMENT '是否已经上传转介绍截图 1：是，0：否',
    `fp_cc_org`          tinyint(1)                                                       DEFAULT '0' COMMENT '线索分配到cc的分配来源\n1：公有池\n2：tmk池',
    `note_return_time`   int(11)                                                          DEFAULT '0' COMMENT '线索回访时间',
    `act_status`         int(11)                                                          DEFAULT '0' COMMENT 'tmk激活状态；0待激活，1未激活，2已激活，3无效；',
    `act_type`           int(11)                                                          DEFAULT '0' COMMENT 'TMK激活类型（子状态）',
    `act_pool`           int(11)                                                          DEFAULT '0' COMMENT 'TMK激活池,0默认,1未激活池,2激活失败池,3无效池,4已激活池',
    `edit_cc_time`       int(11)                                                          DEFAULT '0' COMMENT '修改CC时间(分配CC时间)',
    `edit_tmk_time`      int(11)                                                          DEFAULT '0' COMMENT '修改TMK时间(分配TMK时间)',
    `is_new`             tinyint(1)                                                       DEFAULT '1' COMMENT '是否新线索,1是,0否',
    `open_rec`           int(11)                                                          DEFAULT '0' COMMENT '是否开启自动回收规则扫描，0开启，大于0不开启，大于0为锁定到期时间，到期后置零开启自动回收规则扫描',
    `repool`             tinyint(1)                                                       DEFAULT '0' COMMENT '公海池，1CC公海池，2tmk公海池',
    `referee`            int(11)                                                          DEFAULT '0' COMMENT '推荐人（新）',
    `referee_master`     int(11)                                                          DEFAULT '0' COMMENT '教务id',
    `flow_plan`          tinyint(2)                                                       DEFAULT '0' COMMENT '跟进进度，同note表',
    `re_comm`            tinyint(1)                                                       DEFAULT '0' COMMENT '入公海原因',
    `re_time`            int(11)                                                          DEFAULT '0' COMMENT '入公海时间',
    `callstatus`         tinyint(1)                                                       DEFAULT '0' COMMENT '0:空闲，1：呼叫中———废弃',
    `calltime`           int(11)                                                          DEFAULT '0' COMMENT '呼叫结束的时间———废弃',
    `lockoperator`       int(11)                                                          DEFAULT '0' COMMENT '0：未锁定\n大于0 ：锁定的adminID',
    `master_fptime`      int(11)                                                          DEFAULT '0' COMMENT '教务的分配时间',
    `channel_level`      varchar(2) CHARACTER SET utf8 COLLATE utf8_general_ci            DEFAULT '' COMMENT '渠道等级',
    `buylesstatus`       tinyint(1)                                                       DEFAULT '0' COMMENT '缴费用户上课情况状态，\n0：默认\n1：定金不开课\n2：未开课\n3：正常上课\n4：正常待续费\n5：沉默停课\n6：退费结课\n7：结课待续费\n8：结课不续费',
    `groupqrcode`        varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci          DEFAULT NULL COMMENT '群二维码',
    `flowtotal`          int(11)                                                          DEFAULT '0' COMMENT '跟进总次数',
    `groupqrcode_uptime` int(11)                                                 NOT NULL DEFAULT '0' COMMENT '群二维码上传时间',
    `groupqrcode_upuser` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci  NOT NULL DEFAULT '' COMMENT '群二维码上传人',
    PRIMARY KEY (`id`),
    KEY `status_substat` (`status`, `substatus`),
    KEY `life` (`life`),
    KEY `apk` (`apk`),
    KEY `pc` (`pc`),
    KEY `flowstatus` (`flowstatus`),
    KEY `ctime` (`ctime`),
    KEY `fp_tags` (`fp_tags`),
    KEY `sales` (`sales`),
    KEY `mobile` (`mobile`),
    KEY `tmkpool` (`tmkpool`),
    KEY `tmk` (`tmk`),
    KEY `region` (`region`),
    KEY `referee_master` (`referee_master`),
    KEY `referee` (`referee`),
    KEY `edit_cc_time` (`edit_cc_time`),
    KEY `master_id` (`master`),
    KEY `flowtotal` (`flowtotal`),
    KEY `parent` (`parent`),
    KEY `idx_username` (`username`),
    KEY `idx_parent` (`parent`),
    KEY `idx_master_flowstatus_del_status` (`master`, `flowstatus`, `del`, `status`),
    KEY `idx_recomm_del_retime` (`re_comm`, `del`, `re_time`),
    KEY `idx_channel_del` (`channel`, `del`),
    KEY `idx_flowstatus_buy_time` (`flowstatus`, `f_buy_time`)
) ENGINE = InnoDB COMMENT ='用户表';